CREATE TABLE ACCOUNTS(
	   userID VARCHAR2(20)	PRIMARY KEY
	 , userPW VARCHAR2(20)
	 , name VARCHAR2(20)
	 , gender CHAR(1)		CHECK(GENDER IN('M','F')) 
	 , age NUMBER
	 , join_date DATE
);

DROP TABLE ACCOUNTS;

DELETE FROM ACCOUNTS WHERE userID = 'hong';

SELECT * FROM ACCOUNTS;