DROP SEQUENCE SEQ_TEST;

CREATE SEQUENCE SEQ_TEST
		  START WITH 300
	  INCREMENT BY 5
	   MAXVALUE 310
	   MINVALUE 290
	      CYCLE
	    NOCACHE;
	  
ALTER SEQUENCE SEQ_TEST
--		  START WITH 300
	  INCREMENT BY 5
	   MAXVALUE 310
	      CYCLE
	    NOCACHE;	  
	   
SELECT SEQ_TEST.CURRVAL FROM DUAL;

SELECT SEQ_TEST.NEXTVAL FROM DUAL;

SELECT NVL(NULL, '0') FROM DUAL;

CREATE SEQUENCE SEQ_TEST NOCACHE; 