CREATE TABLE CASHBOOK(
	   serial_num INTEGER		CONSTRAINT PK_CASHBOOK_SERIAL_NUM PRIMARY KEY
	 , transaction_date DATE	CONSTRAINT NN_CASHBOOK_TRANSACTION_DATE NOT NULL 
	 , site_name VARCHAR(60)	CONSTRAINT NN_CASHBOOK_SITE_NAME NOT NULL
	 , breakdown VARCHAR(100)	CONSTRAINT NN_CASHBOOK_BREAKDOWN NOT NULL
	 , deposit INTEGER
	 , expense INTEGER
	 , note_num INTEGER			CONSTRAINT FK_CASHBOOK_NOTE_NUM REFERENCES NOTE(note_num)
);

CREATE TABLE NOTE(
	   note_num INTEGER			CONSTRAINT PK_NOTE_NOTE_NUM PRIMARY KEY
	 , note_name VARCHAR(30)
);

DROP TABLE CASHBOOK;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'CASHBOOK';

CREATE SEQUENCE SQU_SNUM NOCACHE;

INSERT INTO NOTE VALUES (1, '자재비');
INSERT INTO NOTE VALUES (2, '경비');
INSERT INTO NOTE VALUES (3, '식비');
INSERT INTO NOTE VALUES (4, '인건비');

DELETE FROM CASHBOOK WHERE SERIAL_NUM=8;

SELECT * FROM CASHBOOK;
SELECT * FROM NOTE;
SELECT TRANSACTION_DATE
	 , SITE_NAME
	 , BREAKDOWN
	 , DEPOSIT
	 , EXPENSE
	 , NOTE_NAME
  FROM CASHBOOK C
  JOIN NOTE N
    ON N.NOTE_NUM = C.NOTE_NUM;
 WHERE TRANSACTION_DATE >= '2021-01-01' AND TRANSACTION_DATE <= '2021-02-05';

SELECT * FROM CASHBOOK
 WHERE TRANSACTION_DATE BETWEEN CONVERT(DATE, '2021-01-01') AND CONVERT(DATE, '2021-05-05'); 


INSERT INTO CASHBOOK VALUES (
	   SQU_SNUM.NEXTVAL
	 , '2021-01-15'
	 , '해양3중학교'
	 , '진한식당'
	 , NULL
	 , 49500
	 , 3
);

INSERT INTO CASHBOOK VALUES (
	   SQU_SNUM.NEXTVAL
	 , '2021-02-17'
	 , '해양3중학교'
	 , '진한식당'
	 , NULL
	 , 126500
	 , 3
);

INSERT INTO CASHBOOK VALUES (
	   SQU_SNUM.NEXTVAL
	 , '2021-03-04'
	 , '해양3중학교'
	 , '수금/1월기성'
	 , NULL
	 , 7000000
	 , 1
);

UPDATE CASHBOOK SET TRANSACTION_DATE = 
				  , SITE_NAME = 'test'
				  , BREAKDOWN = 'test'
				  , DEPOSIT = 0
				  , EXPENSE = 20000
				  , NOTE_NUM = 1
			  WHERE SERIAL_NUM = 10;
SELECT * FROM CASHBOOK;