DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;
DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
       ID NUMBER NOT NULL
	 , TITLE VARCHAR2(100) NOT NULL
	 , CONTENT VARCHAR2(2000)
	 , EMPID NUMBER NOT NULL
	 , CREATEDATE DATE DEFAULT(SYSDATE)
	 , CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID)
	 , CONSTRAINT EMP_BOARDS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE SEQUENCE EMP_BOARDS_SEQ NOCACHE;
SELECT * FROM EMP_BOARDS;

-- 게시판 글을 등록하기 전에 ID 번호를 자동으로 생성하여 가져오기 위한 쿼리
SELECT EMP_BOARDS_SEQ.NEXTVAL FROM DUAL;

-- 게시판 글을 등록하기 위한 쿼리
INSERT INTO EMP_BOARDS(ID, TITLE, CONTENT, EMPID, CREATEDATE)
	 VALUES (#{id}, #{title}, #{content}, #{empId}, SYSDATE);